import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ToolPage } from '@/components/layout/ToolPage';
import { hourlyTimes, parseTime } from '@/lib/calc/military-time';
import { buildMetadata } from '@/lib/seo/metadata';
export const dynamicParams=false;
export function generateStaticParams(){return hourlyTimes.map(hhmm=>({hhmm}));}
export async function generateMetadata({params}:{params:Promise<{hhmm:string}>}){const {hhmm}=await params;if(!hourlyTimes.includes(hhmm))notFound();const r=parseTime(hhmm);return buildMetadata({title:`${hhmm} Military Time = ${r.twelve}`,description:`${hhmm} is ${r.twelve}. Learn pronunciation and compare the preceding and following hours.`,path:'/military-time/'+hhmm});}
export default async function Page({params}:{params:Promise<{hhmm:string}>}){const {hhmm}=await params;if(!hourlyTimes.includes(hhmm))notFound();const r=parseTime(hhmm);const i=hourlyTimes.indexOf(hhmm);const previous=hourlyTimes[(i+23)%24]!;const next=hourlyTimes[(i+1)%24]!;return <ToolPage title={`What is ${hhmm} in military time?`} path={'/military-time/'+hhmm} calculator={false} summary={`${hhmm} means ${r.twelve}. Pronounce it “${r.pronunciation}.”`} meta={{retrievedAt:'2026-10-07T10:00:00Z',sourceUrls:['https://www.time.gov/']}} how={<p>The hour is {r.hour}, with zero minutes. {r.hour===0?'At midnight, 00 becomes 12 AM.':r.hour===12?'12 is noon, so this is 12 PM.':r.hour>12?`Subtract 12 from ${r.hour} to get ${r.hour-12} PM.`:`The hour stays ${r.hour} and uses AM.`} The clock format does not specify a time zone.</p>} faq={[{question:'Is this the same as UTC?',answer:'Only if the time is explicitly labeled Zulu or UTC.'},{question:'Can I convert minutes too?',answer:'Yes. The main converter accepts any valid hour and minute.'},{question:'Which hour comes next?',answer:`${next} is ${parseTime(next).twelve}.`}]}><div className="rounded-2xl border border-border bg-white p-8 text-4xl font-bold">{hhmm} = {r.twelve}</div><nav aria-label="Adjacent hours" className="flex flex-wrap gap-6"><Link className="text-link" href={'/military-time/'+previous}>← {previous} ({parseTime(previous).twelve})</Link><Link className="text-link" href={'/military-time/'+next}>{next} ({parseTime(next).twelve}) →</Link></nav><Link className="text-link" href="/military-time">Open the two-way time converter</Link></ToolPage>;}

