import { notFound } from 'next/navigation';
import { getVaRates } from '@/lib/data/benefits';
import { ToolPage } from '@/components/layout/ToolPage';
import { DataTable } from '@/components/tables/DataTable';
import { buildMetadata } from '@/lib/seo/metadata';
import { formatUSD } from '@/lib/format';
export const dynamicParams=false;
export function generateStaticParams(){return [{year:'2026'}];}
export async function generateMetadata({params}:{params:Promise<{year:string}>}){const {year}=await params;return buildMetadata({title:`VA Disability Compensation Rates ${year}`,description:'Official VA disability payment tables, dependent-status rows, and added amounts.',path:'/va-disability/rates/'+year});}
export default async function Page({params}:{params:Promise<{year:string}>}){const {year}=await params;if(year!=='2026')notFound();const data=getVaRates();return <ToolPage title="VA Disability Compensation Rates (2026)" path="/va-disability/rates/2026" calculator={false} summary="Exact monthly payment amounts from VA, effective December 1, 2025. Choose the row that matches your eligible dependents." meta={data.meta} how={<p>Base amounts include the dependents named in that row. When there is more than one eligible child under 18, add the additional-child amount for each child after the first. School-age-child and spouse Aid and Attendance allowances are listed separately.</p>} faq={[{question:'When do these rates take effect?',answer:'December 1, 2025. This is the table VA identifies as 2026 rates.'},{question:'Can I receive extra compensation for a spouse?',answer:'A dependent spouse can affect compensation at ratings of 30% or more.'},{question:'Are these calculator estimates?',answer:'These tables reproduce the published amounts; eligibility and your final award are determined by VA.'}]}><DataTable caption="10% and 20% · monthly compensation" rows={Object.entries(data.lowRatings).map(([rating,amount])=>({rating,amount}))} rowKey={r=>r.rating} columns={[{key:'rating',label:'Rating',render:r=>r.rating+'%'},{key:'amount',label:'Monthly',numeric:true,render:r=>formatUSD(r.amount)}]}/>{[{title:'Spouse or parents, no children',rows:data.rates},{title:'Dependents including one child',rows:data.children},{title:'Added amounts',rows:data.added}].map(group=><DataTable key={group.title} caption={group.title+' · monthly compensation'} rows={group.rows} rowKey={r=>r.label} columns={[{key:'label',label:'Dependent status',render:r=>r.label},...[30,40,50,60,70,80,90,100].map(rating=>({key:String(rating),label:rating+'%',numeric:true,render:(row:{amounts:Record<string,number>})=>formatUSD(row.amounts[String(rating)]!)}))]}/>)}</ToolPage>;}
