import { PerDiemInsights } from '@/components/data/PerDiemInsights';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPerDiem, getLocation, getMieBreakdown, perDiemParams } from '@/lib/data/per-diem';
import { ToolPage } from '@/components/layout/ToolPage';
import { DataTable } from '@/components/tables/DataTable';
import { StatTile } from '@/components/ui';
import { buildMetadata } from '@/lib/seo/metadata';
import { formatUSD, formatPercent } from '@/lib/format';
export const dynamicParams=false;
export function generateStaticParams(){return perDiemParams();}
type Props={params:Promise<{state:string;location:string}>};
export async function generateMetadata({params}:Props){const {state,location}=await params;const l=getLocation('FY2027',state,location)??getLocation('FY2026',state,location);return buildMetadata({title:`${(l?.name??'Locality').slice(0,27)} Per Diem FY2027`,description:'Official GSA lodging seasons, meal breakdown, county coverage, and comparison with the standard CONUS rate.',path:`/per-diem/${state}/${location}`});}
export default async function Page({params}:Props){const {state,location}=await params;const data=getPerDiem();const current=getLocation('FY2027',state,location);const old=getLocation('FY2026',state,location);const l=current??old;if(!l)notFound();const mie=getMieBreakdown('FY2027',current?.mie??data.standard.mie);const seasons=current?.seasons??[{start:data.meta.effectiveFrom,end:data.meta.effectiveTo!,lodging:data.standard.lodging}];const peak=Math.max(...seasons.map(s=>s.lodging));return <ToolPage title={`${l.name}, ${l.state} Per Diem Rates (FY2027)`} path={`/per-diem/${state}/${location}`} calculator={false} summary={current?`Lodging ranges from ${formatUSD(Math.min(...seasons.map(s=>s.lodging))*100)} to ${formatUSD(peak*100)} per night, plus ${formatUSD(mie.mie*100)} M&IE.`:'This locality was listed in FY2026. It uses the standard CONUS rate in FY2027; confirm current coverage with GSA.'} meta={data.meta} how={<><p>Use the exact season covering your stay. Covered counties: {l.counties.join(', ')}. Lodging taxes are excluded.</p><p>For a one-night trip at this area’s peak, the lodging and first/last-day meal allowance total {formatUSD((peak+mie.firstLast*2)*100)} before meal deductions. <Link className="text-link" href="/per-diem/calculator">Calculate your trip</Link>.</p></>} faq={[{question:'Are taxes included?',answer:'Lodging taxes are separate. Confirm reimbursement with your travel office.'},{question:'What is the first and last day rate?',answer:`Published M&IE for each first/last travel day is ${formatUSD(mie.firstLast*100)}.`},{question:'What if my city is not listed?',answer:'Check county coverage first. Otherwise a CONUS location generally uses the standard rate.'}]}><div className="grid gap-4 sm:grid-cols-3"><StatTile label="Peak lodging" value={formatUSD(peak*100)}/><StatTile label="Above standard lodging" value={formatPercent(peak/data.standard.lodging-1)}/><StatTile label="Peak change vs FY2026" value={old?formatPercent(peak/Math.max(...old.seasons.map(s=>s.lodging))-1):'New'}/></div><DataTable caption="Exact lodging seasons · FY2027" rows={seasons} rowKey={s=>s.start} columns={[{key:'start',label:'From',render:s=>s.start},{key:'end',label:'Through',render:s=>s.end},{key:'rate',label:'Nightly cap',numeric:true,render:s=>formatUSD(s.lodging*100)}]}/><DataTable caption="Published meals and incidental expenses" rows={[{name:'Breakfast',value:mie.breakfast},{name:'Lunch',value:mie.lunch},{name:'Dinner',value:mie.dinner},{name:'Incidentals',value:mie.incidentals},{name:'Full day',value:mie.mie},{name:'First / last day',value:mie.firstLast}]} rowKey={r=>r.name} columns={[{key:'name',label:'Allowance',render:r=>r.name},{key:'value',label:'Amount',numeric:true,render:r=>formatUSD(r.value*100)}]}/><PerDiemInsights state={state} slug={location}/><Link className="text-link" href={'/per-diem/'+state}>All areas in this state</Link></ToolPage>;}

