import Link from 'next/link';
import { Calculator, ArrowUpRight } from 'lucide-react';
import { navigationRoutes, routeHref, trustRoutes } from '@/lib/routes';
import { site } from '@/lib/site';
import { Container } from './Container';
/** Shared navigation and the required independence statement. */
export function Footer() {
  return <footer className="site-footer"><Container><div className="grid gap-10 md:grid-cols-[1.3fr_1fr_1fr]"><div><Link href="/" className="inline-flex items-center text-xl font-bold tracking-tight text-white"><span className="brand-mark"><Calculator size={21} aria-hidden="true" /></span>MegaTools</Link><p className="mt-5 max-w-xs text-sm leading-7">A little clarity for your next decision. Free tools for military members, veterans, families, and federal employees.</p><Link href="/sources" className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-teal-200">Explore our sources <ArrowUpRight size={16} aria-hidden="true" /></Link></div><nav aria-label="Footer tools"><h2 className="mb-5 text-xs font-bold uppercase tracking-widest text-white">Your toolkit</h2><ul className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">{navigationRoutes.map((route) => <li key={route.path}><Link href={routeHref(route)} className="inline-flex min-h-10 items-center">{route.navTitle}</Link></li>)}</ul></nav><nav aria-label="About MegaTools"><h2 className="mb-5 text-xs font-bold uppercase tracking-widest text-white">About &amp; resources</h2><ul className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">{trustRoutes.map((route) => <li key={route.path}><Link href={route.path} className="inline-flex min-h-10 items-center">{route.title}</Link></li>)}</ul></nav></div><div className="mt-10 border-t border-slate-600 pt-6 text-xs leading-6"><p className="max-w-4xl">{site.disclaimer}</p><div className="mt-5 flex flex-wrap justify-between gap-2 text-slate-300"><p>© {new Date().getUTCFullYear()} MegaTools. All rights reserved.</p><p>Independent tools. Informed decisions.</p></div></div></Container></footer>;
}
