import Link from 'next/link';
import { getPerDiem, getStates } from '@/lib/data/per-diem';
import { PerDiemSearch } from '@/components/tools/PerDiemCalculator';
import { ToolPage } from '@/components/layout/ToolPage';
import { DataTable } from '@/components/tables/DataTable';
import { buildMetadata } from '@/lib/seo/metadata';
import { formatUSD } from '@/lib/format';
import { stateFromSlug } from '@/lib/slug';
export function generateMetadata(){return buildMetadata({title:'CONUS Per Diem Rates FY2027',description:'Search official GSA lodging and meal rates by city or ZIP. Explore state and locality rates or calculate a trip.',path:'/per-diem'});}
export default function Page(){const data=getPerDiem();const index=data.locations.map((l)=>({key:l.stateSlug+'/'+l.slug,name:l.name,state:l.state}));const top=[...data.locations].sort((a,b)=>Math.max(...b.seasons.map(s=>s.lodging))-Math.max(...a.seasons.map(s=>s.lodging))).slice(0,25);return <ToolPage title="CONUS Per Diem Rates (FY2027)" path="/per-diem" calculator={false} summary={`Standard CONUS per diem: ${formatUSD(data.standard.lodging*100)} lodging + ${formatUSD(data.standard.mie*100)} M&IE per day, effective October 1, 2026.`} meta={data.meta} how={<><p>GSA sets location-specific lodging caps and meals and incidental expense rates. Lodging excludes taxes. The first and last travel days use GSA’s published 75% M&amp;IE amounts.</p><p>A one-night trip at the standard rate permits {formatUSD((data.standard.lodging+data.standard.mie*1.5)*100)} before any meal deductions. Use the calculator for exact seasonal and fiscal-year changes.</p></>} faq={[{question:'What if my city is not listed?',answer:'Check the county coverage; a listed county may cover your city. Otherwise, a CONUS location uses the standard rate.'},{question:'Are Alaska and Hawaii included?',answer:'No. GSA CONUS covers the contiguous states and DC. DoD publishes OCONUS rates.'},{question:'Do rates include lodging taxes?',answer:'No. Confirm separately reimbursable taxes with your agency.'}]}><PerDiemSearch locations={index}/><p><Link className="text-link" href="/per-diem/calculator">Open the trip calculator →</Link></p><section><h2 className="section-title">Browse by state</h2><ul className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{getStates('FY2027').map((state)=><li key={state}><Link className="text-link" href={'/per-diem/'+state}>{stateFromSlug(state)?.name}</Link></li>)}</ul></section><DataTable caption="Highest peak lodging rates · FY2027" rows={top} rowKey={l=>l.id} columns={[{key:'location',label:'Location',render:l=><Link className="text-link" href={'/per-diem/'+l.stateSlug+'/'+l.slug}>{l.name}, {l.state}</Link>},{key:'lodging',label:'Peak lodging',numeric:true,render:l=>formatUSD(Math.max(...l.seasons.map(s=>s.lodging))*100)},{key:'mie',label:'M&IE',numeric:true,render:l=>formatUSD(l.mie*100)}]}/></ToolPage>;}
