import { JsonLd } from '@/components/seo/JsonLd';
import { website, organization, breadcrumbList } from '@/lib/seo/jsonld';
import { buildMetadata } from '@/lib/seo/metadata';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, ShieldCheck, RefreshCw, CircleDollarSign } from 'lucide-react';
import { Container, PageHeader } from '@/components/layout/Container';
import { Badge, Card } from '@/components/ui';
import { UpdatesList } from '@/components/data/UpdatesList';
import { navigationRoutes, routeHref } from '@/lib/routes';
export function generateMetadata(): Metadata { return buildMetadata({ path: '/', title: 'Military & Federal Pay Calculators', description: 'Free military and federal pay tools. Explore per diem, BAH, military pay, VA disability, PCS, GI Bill, retirement, and military time.' }); }
export default function Home() {
  return <><JsonLd data={website()} /><JsonLd data={organization()} /><JsonLd data={breadcrumbList([{ label: 'Home', href: '/' }])} /><section className="border-b border-border bg-white py-14 sm:py-20"><Container><PageHeader eyebrow="Built for your next decision" title="Military & Federal Pay Calculators" summary="Clear answers for military members, veterans, and families. Explore free calculators and rate lookups built around official sources." /><div className="flex flex-wrap gap-x-8 gap-y-3 text-sm font-medium text-primary">{[{ icon: ShieldCheck, text: 'Official sources' }, { icon: RefreshCw, text: 'Dated rate tables' }, { icon: CircleDollarSign, text: 'Free' }].map(({ icon: Icon, text }) => <span key={text} className="flex items-center gap-2"><Icon size={18} aria-hidden="true" />{text}</span>)}</div></Container></section><Container className="py-12 sm:py-16"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><h2 className="section-title mb-0">Find your tool</h2><p className="text-sm text-muted">Choose a calculator to get started.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{navigationRoutes.map((route, index) => <Card key={route.path} id={routeHref(route).startsWith('/#') ? routeHref(route).slice(2) : undefined} className="scroll-mt-8 flex flex-col"><div className="mb-5 flex items-center justify-between gap-3"><span className="text-xs font-semibold tabular-nums text-muted">{String(index + 1).padStart(2, '0')}</span>{route.status === 'soon' && <Badge>Coming soon</Badge>}</div><h3 className="text-xl font-bold text-primary">{route.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-muted">{route.description}</p>{route.status === 'live' && <Link href={route.path} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">Open tool <ArrowUpRight size={16} aria-hidden="true" /></Link>}</Card>)}</div><section className="mt-14 rounded-2xl border border-border bg-white p-6 sm:p-8"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="section-title mb-0">Latest data updates</h2><Link href="/updates" className="text-link text-sm">All updates</Link></div><UpdatesList limit={3} /></section><div className="mt-10 flex flex-wrap gap-6 text-sm"><Link href="/sources" className="text-link">See our official sources</Link><Link href="/about" className="text-link">How we build MegaTools</Link></div></Container></>;
}

