export type Condition={rating:number;side:'none'|'left-arm'|'right-arm'|'left-leg'|'right-leg'};
function combine(values:number[]){let total=0;const steps:{rating:number;combined:number}[]=[];for(const rating of [...values].sort((a,b)=>b-a)){total=Math.round(total+rating*(100-total)/100);steps.push({rating,combined:total});}return {exact:total,rating:Math.min(100,Math.round(total/10)*10),steps};}
/** CFR 4.25 intermediate whole-number rounding; 4.26(d) favors the veteran. */
export function vaCombined(conditions:Condition[]){if(conditions.length>12)throw new Error('Maximum 12 conditions.');if(conditions.some(c=>!Number.isInteger(c.rating)||c.rating<0||c.rating>100||c.rating%10!==0))throw new Error('Use ratings from 0 to 100 in increments of 10.');
 const eligible=conditions.map((condition,index)=>({...condition,index})).filter(c=>c.rating>0&&c.side!=='none'&&conditions.some(other=>other.rating>0&&other.side===c.side.replace('left','TEMP').replace('right','left').replace('TEMP','right')));
 let best={...combine(conditions.map(c=>c.rating)),bilateral:0};
 // At most 12 conditions keeps exhaustive 4.26(d) exception evaluation bounded.
 for(let mask=0;mask<(1<<eligible.length);mask++){const selected=eligible.filter((_,i)=>mask&(1<<i));if(selected.length<2)continue;const sides=new Set(selected.map(c=>c.side));if(selected.some(c=>!sides.has(c.side.replace('left','TEMP').replace('right','left').replace('TEMP','right') as Condition['side'])))continue;const ids=new Set(selected.map(c=>c.index));const subtotal=combine(selected.map(c=>c.rating)).exact;const adjusted=Math.round(subtotal*1.1);const result=combine([...conditions.filter((_,i)=>!ids.has(i)).map(c=>c.rating),adjusted]);if(result.rating>best.rating||(result.rating===best.rating&&result.exact>best.exact))best={...result,bilateral:adjusted};}
 return best;
}
export type VaRates={lowRatings:Record<string,number>;rates:{amounts:Record<string,number>}[];children:{amounts:Record<string,number>}[];added:{amounts:Record<string,number>}[]};
export function vaCompensation(data:VaRates,rating:number,{spouse,parents,children,school,attendance}:{spouse:boolean;parents:number;children:number;school:number;attendance:boolean}){if(![parents,children,school].every(Number.isInteger)||parents<0||parents>2||children<0||school<0)throw new Error('Invalid dependent counts.');if(rating===0)return 0;if(rating<30)return data.lowRatings[String(rating)]??0;const row=spouse?1+parents:parents===0?0:parents+3;const childRow=spouse?1+parents:parents===0?0:parents+3;const base=(children>0?data.children[childRow]:data.rates[row])?.amounts[String(rating)];if(base===undefined)throw new Error('Missing VA rate.');return base+Math.max(0,children-1)*(data.added[0]?.amounts[String(rating)]??0)+school*(data.added[1]?.amounts[String(rating)]??0)+(spouse&&attendance?(data.added[2]?.amounts[String(rating)]??0):0);}
