import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPerDiem, getStates, getLocationsByState, getLocation } from '@/lib/data/per-diem';
import { ToolPage } from '@/components/layout/ToolPage';
import { DataTable } from '@/components/tables/DataTable';
import { buildMetadata } from '@/lib/seo/metadata';
import { stateFromSlug } from '@/lib/slug';
import { formatUSD, formatPercent } from '@/lib/format';
export const dynamicParams=false;
export function generateStaticParams(){return getStates('FY2027').map(state=>({state}));}
export async function generateMetadata({params}:{params:Promise<{state:string}>}){const {state}=await params;return buildMetadata({title:`${stateFromSlug(state)?.name??'State'} Per Diem FY2027`,description:'Official GSA location rates, seasonal lodging ranges, meal allowances, and year-over-year changes.',path:'/per-diem/'+state});}
export default async function Page({params}:{params:Promise<{state:string}>}){const {state}=await params;const name=stateFromSlug(state)?.name;const rows=getLocationsByState('FY2027',state);if(!name||!getStates('FY2027').includes(state))notFound();const data=getPerDiem();return <ToolPage title={`${name} Per Diem Rates (FY2027)`} path={'/per-diem/'+state} calculator={false} summary={`All other CONUS locations in ${name} use ${formatUSD(data.standard.lodging*100)} lodging and ${formatUSD(data.standard.mie*100)} M&IE unless covered by a listed county.`} meta={data.meta} how={<p>Choose the locality that covers your work location. Seasonal caps vary by date. Compare the FY2027 peak with FY2026 below; taxes are excluded.</p>} faq={[{question:'Which county is covered?',answer:'Open a locality for its published coverage and exact season dates.'},{question:'What if I travel across October 1?',answer:'The trip calculator selects the fiscal year for each travel date.'},{question:'Where can I confirm my rate?',answer:'Use the GSA source files linked below or confirm with your travel office.'}]}><p className="text-sm text-muted">{rows.length} published non-standard {rows.length===1?'area':'areas'} in this state. {rows.length===0&&'All locations use the standard CONUS rate.'}</p><DataTable caption={`${name} non-standard areas`} rows={rows} rowKey={l=>l.id} columns={[{key:'name',label:'Area',render:l=><Link className="text-link" href={'/per-diem/'+state+'/'+l.slug}>{l.name}</Link>},{key:'lodging',label:'Lodging range',numeric:true,render:l=>`${formatUSD(Math.min(...l.seasons.map(s=>s.lodging))*100)}–${formatUSD(Math.max(...l.seasons.map(s=>s.lodging))*100)}`},{key:'mie',label:'M&IE',numeric:true,render:l=>formatUSD(l.mie*100)},{key:'change',label:'Peak YoY',numeric:true,render:l=>{const old=getLocation('FY2026',state,l.slug);return old?formatPercent(Math.max(...l.seasons.map(s=>s.lodging))/Math.max(...old.seasons.map(s=>s.lodging))-1):'New locality';}}]}/></ToolPage>;}

