import type { ToolMeta } from '@/lib/tools/types';

const meta: ToolMeta = {
  slug: 'uuid-generator',
  category: 'developer',
  name: 'UUID Generator',
  h1: 'UUID Generator',
  metaTitle: 'UUID Generator — Version 4 and Version 7',
  metaDescription:
    'Generate RFC 9562 UUIDs in your browser — random version 4 or time-ordered version 7 — in batches, with the version and variant bits laid out and explained.',
  shortDescription:
    'Generate version 4 or time-ordered version 7 UUIDs in batches, with the bit layout of each one shown rather than assumed.',
  leadAnswer:
    'A UUID is a 128-bit identifier that any machine can generate on its own, without asking a central authority, and still expect to be unique. Version 4 fills 122 of those bits with random data. Version 7 replaces the leading 48 with a Unix millisecond timestamp, so the identifiers sort in creation order.',
  keywords: [
    'uuid generator',
    'guid generator',
    'uuid v4 generator',
    'uuid v7 generator',
    'random uuid',
    'rfc 9562',
  ],
  faqs: [
    {
      question: 'Are these UUIDs generated on a server?',
      answer:
        'No. Generation runs entirely in your browser using crypto.getRandomValues, which draws from your operating system cryptographically secure random number generator. Nothing is transmitted, logged or stored, and the page keeps working with the network disconnected. You can confirm it by opening your browser network tools and watching that generating produces no request.',
    },
    {
      question: 'What is the difference between UUID v4 and UUID v7?',
      answer:
        'Version 4 is 122 bits of randomness and nothing else, so consecutive UUIDs are scattered with no relationship to each other. Version 7 puts a 48-bit Unix millisecond timestamp in the leading bits and fills the remaining 74 with randomness, so sorting a list of them sorts by creation time. Both are unique in practice; version 7 is additionally ordered, which is what makes it kinder to database indexes.',
    },
    {
      question: 'Can two randomly generated UUIDs ever be the same?',
      answer:
        'It is possible but not something to plan around. A version 4 UUID carries 122 random bits, and by the birthday bound you would need roughly 2.7 quintillion of them before there was an even chance of a single collision. At a million generated every second that is about 87,000 years. The practical risks are a broken random source or a buggy generator, not the mathematics.',
    },
    {
      question: 'Is a GUID the same thing as a UUID?',
      answer:
        'Yes, for almost every purpose. GUID is the name Microsoft uses for the same 128-bit identifier, and a GUID generated by modern Windows APIs is a conforming version 4 UUID. The one difference worth knowing is textual: some Microsoft tooling writes them wrapped in braces, and some older Microsoft formats store the first three fields little-endian, which changes the byte order without changing the value.',
    },
    {
      question: 'Should I use a UUID as a primary key?',
      answer:
        'It depends on the version and the database. A random version 4 key inserted into a clustered B-tree index writes to a different page nearly every time, which fragments the index and hurts write throughput as the table grows. A version 7 key is monotonic at millisecond resolution, so inserts land at the end of the index the way an auto-increment integer does, while keeping the property that clients can generate keys offline.',
    },
    {
      question: 'Does a version 7 UUID leak when a record was created?',
      answer:
        'Yes, and that is the trade. The leading 48 bits are a plain Unix timestamp in milliseconds, readable by anyone holding the identifier. If your identifiers are public and the creation time is sensitive — an account age, a document date, the order in which two records were made — use version 4 instead. It carries no timestamp at all.',
    },
    {
      question: 'Why does every UUID here have a 4 or a 7 in the same place?',
      answer:
        'That character is the version field, and it is fixed by the specification rather than random. The first character of the fourth group is the variant field, which is why it is always 8, 9, a or b on a conforming UUID. Between them those two fields consume 6 of the 128 bits, which is why a version 4 UUID carries 122 bits of randomness rather than 128.',
    },
  ],
  sources: [
    {
      title: 'RFC 9562 — Universally Unique IDentifiers (UUIDs)',
      publisher: 'Internet Engineering Task Force (IETF)',
      url: 'https://www.rfc-editor.org/rfc/rfc9562.html',
    },
    {
      title: 'RFC 4122 — A Universally Unique IDentifier (UUID) URN Namespace (obsoleted by RFC 9562)',
      publisher: 'Internet Engineering Task Force (IETF)',
      url: 'https://www.rfc-editor.org/rfc/rfc4122.html',
    },
    {
      title: 'Crypto.getRandomValues() — Web Crypto API specification and behaviour',
      publisher: 'MDN Web Docs (Mozilla)',
      url: 'https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues',
    },
  ],
  relatedSlugs: ['developer/unix-timestamp-converter', 'developer/password-generator'],
  publishedAt: '2026-08-11',
  updatedAt: '2026-08-11',
};

export default meta;
